server:
  port: 8080
  context-path: /api
zuul:
  debug:
    request: true
  routes:
    users:
      path: /users/**
      url: http://localhost:8081
      stripPrefix: false
    login:
      path: /login
      url: http://localhost:8081
      stripPrefix: false
    verfications:
      path: /verfications
      url: http://localhost:8081
      stripPrefix: false
    todos:
      path: /todos/**
      url: http://localhost:8082
      stripPrefix: false
  sensitive-headers:

logging:
  level:
    org:
      springframework:
        security: TRACE
        cloud:
          netflix: TRACE
