server:
  port: 8080

zuul:
  debug:
    request: true
  routes:
    users:
      path: /users/**
      url: http://localhost:8081
      stripPrefix: false
    login:
      path: /login
      url: http://localhost:8081
      stripPrefix: false
    verfications:
      path: /verfications
      url: http://localhost:8081
      stripPrefix: false
    todos:
      path: /todos/**
      url: http://localhost:8082
      stripPrefix: false
  sensitive-headers:
  prefix: /api

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: TRACE
