spring:
  application:
    name: gateway
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.int}

user-service:
  ribbon:
    listOfServers: localhost:8081
todo-service:
  ribbon:
    listOfServers: localhost:8082


server:
  port: 8080
zuul:
  debug:
    request: true
  routes:
    users:
      path: /users/**
      serviceId: user-service
      stripPrefix: false
    login:
      path: /login
      serviceId: user-service
      stripPrefix: false
    verfications:
      path: /verfications
      serviceId: user-service
      stripPrefix: false
    todos:
      path: /todos/**
      serviceId: todo-service
      stripPrefix: false
  sensitive-headers:
  prefix: /api
logging:
  level:
    org:
      springframework:
        security: DEBUG
        cloud:
          netflix: DEBUG

